org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=renderscale
mod.name=RenderScale
mod.group=dev.zelo
mod.version=1.3.6
mod.channel_tag=
mod.authors=Zelo101
mod.contributors=
mod.license=MIT
mod.description=RenderScale allows you to change Minecraft's render resolution separately from the HUD elements.
mod.sources_url=https://github.com/Zolo101/RenderScale
mod.homepage_url=https://github.com/Zolo101/RenderScale
mod.issues_url=https://github.com/Zolo101/RenderScale/issues
mod.discord_url=https://discord.gg/YVuuF9KB5j

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.forge=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.iris=[VERSIONED]
deps.cloth_config=[VERSIONED]

publish.modrinth=renderscale
publish.curseforge=renderscale
publish.github=true