# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.3.2
group=dev.zelo

org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=5
org.gradle.parallel=true

#deps.minecraft=[VERSIONED]
#deps.neoforge=[VERSIONED]

#deps.parchment=2025.06.15
#deps.cloth_config=[VERSIONED]
#deps.iris=[VERSIONED]
#deps.modmenu=[VERSIONED]
# Common
#org.gradle.java.home=/usr/lib/jvm/java-21-jetbrains/
#minecraft_version=1.21.6
#mod_name=RenderScale
#mod_author=Zelo101
#mod_id=renderscale
#license=MIT
#credits=
#description=RenderScale allows you to change Minecraft's render resolution separately from the HUD elements.
#minecraft_version_range=[1.21.6]
#neo_form_version=1.21.5-20250325.162830
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
#parchment_minecraft=1.21.5
#parchment_version=2025.06.01
# Fabric
#fabric_version=0.127.0+1.21.6
#fabric_loader_version=0.16.14
# Forge (not using)
#forge_version=51.0.17
#forge_loader_version_range=[51,)
# NeoForge
#neoforge_version=21.6.5-beta
#neoforge_loader_version_range=[4,)
# Gradle
#org.gradle.jvmargs=-Xmx3G
#org.gradle.daemon=false

#mod_menu_version=15.0.0-beta.1

#cloth_config_version=19.0.146

#iris_version=1.9.0